language: cpp
compiler:
  - gcc
branches:
  only:
    - master
install:
  - chmod +x ./3rd-party/premake-bin/premake5
  - ./3rd-party/premake-bin/premake5 gmake
script:
  - ls
  - cd projects && make
  - tree
notifications:
  recipients:
    - tynril@gmail.com
  email:
    - on_success: change
    - on_failure: always

